name: project
# channels:

dependencies:
- flask
- selenium
- pytest
- beautifulsoup4
- lxml
- requests

- pip:
  - jupytext
  - jupyter
  - PyFunctional
  - tqdm


  # pip install jupyter_contrib_nbextensions
  # pip install jupyter_nbextensions_configurator
  # jupyter nbextensions_configurator enable --user