name: project
# channels:

dependencies:
- flask
- selenium
- pytest
- beautifulsoup4
# - request

- pip:
  - jupytext
  - jupyter
  - requests


  # pip install jupyter_contrib_nbextensions
  # pip install jupyter_nbextensions_configurator
  # jupyter nbextensions_configurator enable --user